/**********************************************************************************************************************
 * \file App_SystemInit.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "App_Config.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "MCMCAN.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent;
QueueHandle_t g_canRxQueue = NULL;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Low-level hardware initialization */
void hw_init_minimal(void)
{
    /* Enable interrupts */
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
}

/* Initialize all drivers and peripherals */
static void init_drivers(void)
{
    #if (CAN_MODE != LOOPBACK)
    /* Initialize CAN transceiver (P20.6 - STB pin) */
    Driver_Port_Init_CAN_transceiver();
    #endif

    /* Initialize MCMCAN module */
    initMcmcan();
}

/* System initialization task */
void task_system_init(void *arg)
{
    /* Full system initialization */
    init_drivers();

    /* Create CAN RX Queue */
    g_canRxQueue = xQueueCreate(CAN_RX_QUEUE_LENGTH, sizeof(CanRxMessage_t));

    /* Initialize RX message structure */
    IfxCan_Can_initMessage(&g_mcmcan.rxMsg);
    memset((void *)(&g_mcmcan.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Create application tasks */
    xTaskCreate(task_app_led1, "LED1", 512, NULL, tskIDLE_PRIORITY + 1, NULL);
    xTaskCreate(task_app_led2, "LED2", 1024, NULL, tskIDLE_PRIORITY + 2, NULL);
    xTaskCreate(task_can_tx, "CAN_TX", 2048, NULL, tskIDLE_PRIORITY + 3, NULL);
    xTaskCreate(task_can_rx, "CAN_RX", 2048, NULL, tskIDLE_PRIORITY + 4, NULL);
    
    /* Delete self - initialization task is no longer needed */
    vTaskDelete(NULL);
}
