/********************************************************************************************************************
 * \file MCMCAN.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MCMCAN_H_
#define MCMCAN_H_ 1

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdio.h>
#include <string.h>
#include "Ifx_Types.h"
#include "Can/Can/IfxCan_Can.h"
#include "Can/Std/IfxCan.h"
#include "IfxCpu_Irq.h"
#include "IfxPort.h"
#include "Stm/Std/IfxStm.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

/*********************************************************************************************************************/
/*--------------------------------------MODE SELECTION MACRO---------------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * CAN_MODE:
 * - Set to LOOPBACK for internal communication between two nodes
 * - Set to TWO_CONTROLLER_MODE_1 for Board 1 (TX: 0x777, RX: 0x888)
 * - Set to TWO_CONTROLLER_MODE_2 for Board 2 (TX: 0x888, RX: 0x777)
 */

/* Mode definitions */
#define LOOPBACK                    0
#define TWO_CONTROLLER_MODE_1       1
#define TWO_CONTROLLER_MODE_2       2

/* Select mode here */
#define CAN_MODE                    TWO_CONTROLLER_MODE_2       /* Change this value to switch between modes */

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* Message ID configuration based on selected mode */
#if (CAN_MODE == LOOPBACK)
    #define CAN_MESSAGE_ID1         (uint32)0x777           /* TX Message ID (same for loopback)                    */
    #define CAN_MESSAGE_ID2         (uint32)0x777           /* RX Message ID (same for loopback)                    */

#elif (CAN_MODE == TWO_CONTROLLER_MODE_1)
    #define CAN_MESSAGE_ID1         (uint32)0x777           /* TX ID for Board 1                                    */
    #define CAN_MESSAGE_ID2         (uint32)0x888           /* RX ID for Board 1                                    */

#elif (CAN_MODE == TWO_CONTROLLER_MODE_2)
    #define CAN_MESSAGE_ID1         (uint32)0x888           /* TX ID for Board 2                                    */
    #define CAN_MESSAGE_ID2         (uint32)0x777           /* RX ID for Board 2                                    */
#endif

/* Common macros */
#define PIN5                        5                       /* LED1 used in TX ISR is connected to this pin         */
#define PIN6                        6                       /* LED2 used in RX ISR is connected to this pin         */
#define INVALID_RX_DATA_VALUE       0xA5                    /* Used to invalidate RX message data content           */
#define INVALID_ID_VALUE            (uint32)0xFFFFFFFF      /* Used to invalidate RX message ID value               */
#define ISR_PRIORITY_CAN_TX         12
#define ISR_PRIORITY_CAN_RX         13
#define TX_DATA_LOW_WORD            (uint32)0xC0CAC01A      /* Define CAN data lower word to be transmitted         */
#define TX_DATA_HIGH_WORD           (uint32)0xBA5EBA11      /* Define CAN data higher word to be transmitted        */
#define MAXIMUM_CAN_DATA_PAYLOAD    2                       /* Define maximum classical CAN payload in 4-byte words */
#define STM_FREQ_HZ                 100000000ULL
#define CAN_RX_QUEUE_LENGTH         50

/*********************************************************************************************************************/
/*--------------------------------------------------Data Structures--------------------------------------------------*/
/*********************************************************************************************************************/

/* Structure for time data (4 bytes total) */
typedef struct
{
    uint8 hours;      // 0-23
    uint8 minutes;    // 0-59
    uint8 seconds;    // 0-59
    uint8 reserved;   // Padding to make it 4 bytes
} TimeData_t;

/* Structure for CAN message in Queue */
typedef struct
{
    uint32 messageId;
    uint32 counter;        // First 4 bytes
    TimeData_t timeData;   // Next 4 bytes
    uint8 dataLength;
} CanRxMessage_t;

/* Structure for Counter data - separate Tx and Rx counters, independent of MCMCAN module config */
typedef struct
{
    uint32 counterTx;   /* Counter value of the last transmitted message */
    uint32 counterRx;   /* Counter value of the last received message    */
} Counter_t;

/* Structure for Current Time data - separate Tx and Rx time values, independent of MCMCAN module config */
typedef struct
{
    TimeData_t currentTimeTx;   /* Time value of the last transmitted message */
    TimeData_t currentTimeRx;   /* Time value of the last received message    */
} CurrentTime_t;

/* Structure for CAN message in Queue - carries RAW data only, no parsing done in ISR */
typedef struct
{
    uint32 messageId;
    uint32 data[MAXIMUM_CAN_DATA_PAYLOAD];   /* Raw CAN payload, forwarded as-is from ISR */
    uint8  dataLength;
} CanRxMessage_forward_t;

/* MCMCAN module structure - pure CAN peripheral configuration and control, no counter/time data */
typedef struct
{
    IfxCan_Can_Config canConfig;                            /* CAN module configuration structure                   */
    IfxCan_Can canModule;                                   /* CAN module handle                                    */
    IfxCan_Can_Node canSrcNode;                             /* CAN source node handle data structure                */
    IfxCan_Can_Node canDstNode;                             /* CAN destination node handle data structure           */
    IfxCan_Can_NodeConfig canNodeConfig;                    /* CAN node configuration structure                     */
    IfxCan_Filter canFilter;                                /* CAN filter configuration structure                   */
    IfxCan_Message txMsg;                                   /* Transmitted CAN message structure                    */
    IfxCan_Message rxMsg;                                   /* Received CAN message structure                       */
    uint32 txData[MAXIMUM_CAN_DATA_PAYLOAD];                /* Transmitted CAN data array                           */
    uint32 rxData[MAXIMUM_CAN_DATA_PAYLOAD];                /* Received CAN data array                              */
} McmcanType;

/*********************************************************************************************************************/
extern McmcanType          g_mcmcan;
extern Counter_t           g_counter;
extern CurrentTime_t       g_currentTime;
extern QueueHandle_t       g_canRxQueue;
extern IfxPort_Pin_Config  g_led1;
extern IfxPort_Pin_Config  g_led2;
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void initMcmcan(void);
void transmitCanMessage(void);
void initLeds(void);

#if (CAN_MODE != LOOPBACK)
void Driver_Port_Init_CAN_transceiver(void);
//void appWaitMilliseconds(uint32 milliseconds);
#endif

#endif /* MCMCAN_H_ */
